### ISSUE TITLE
npm start failing

### ISSUE THREAD

**Issue by mfmcdonagh** [adasq/gerrit-native-notifications#2]
Hello,
I'm trying to run gerrit-native-notifications, and when i run npm start I get the following error ! 

`[gen] mcdonagm@desktop-mcdonagm ~/Dropbox/dev/gerrit-native-notifications (master)  $ npm start

> gerrit-native-notifications@1.0.0 start /home/mcdonagm/Dropbox/dev/gerrit-native-notifications
> tsc && node ./dist/src/main.js

▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░/home/mcdonagm/Dropbox/dev/gerrit-native-notifications/dist/src/streams/to-native-notification.js:33
    const { title, subtitle, message, url, authorIconPath } = eventDescription;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mcdonagm/Dropbox/dev/gerrit-native-notifications/dist/src/main.js:7:34)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! gerrit-native-notifications@1.0.0 start: `tsc && node ./dist/src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gerrit-native-notifications@1.0.0 start script 'tsc && node ./dist/src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gerrit-native-notifications package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && node ./dist/src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gerrit-native-notifications
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gerrit-native-notifications
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mcdonagm/Dropbox/dev/gerrit-native-notifications/npm-debug.log
`

**Comment by adasq** [comment]
The problem is, that you are using node `4.x`, Typescript compilation target produces `es6` code, which is not fully covered by node `4.x`. That's why es6 destructuring syntax is not recognized. I have changed compilation target from es6 to es5 (https://github.com/adasq/gerrit-native-notifications/commit/548c6880712b5cb5b4aee2dde9731ed97f9a453e) so it should work for you.

**Comment by mfmcdonagh** [comment]
Thanks that worked :)
