### ISSUE TITLE
Retrieve avatars from additional sources

### ISSUE THREAD

**Issue by gkumar7** [adasq/gerrit-native-notifications#5]
Any plans to scrape avatars from other sources, such as jira? Many teams use issue tracking tools alongside code collaboration tools like gerrit. This could provide a new source of features to add to this project. A basic example would be using jira to retrieve more prevalent avatars for gerrit users.

**Comment by adasq** [comment]
Sounds great. I'm open to any changes in this project. If JIRA integration makes sense for you, feel free to post PR. I would love to check how it's done, as JIRA is also a part of my team tools stack.

**Comment by gkumar7** [comment]
Good to hear! Will post a PR soon.

**Comment by gkumar7** [comment]
@adasq, apologies for the extremely high latency here! Hopefully, this feature serves as a neat basis to further improving this project.

**Comment by adasq** [comment]
What I am little bit concern about is an error handling (I think we should inform user about problems) while requesting JIRA API but still, it does not break anything. I have checked it locally and it does work great! Thank you!
